# Generated by Django 5.1.6 on 2025-03-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'max_length': 'Username must be 150 characters or fewer.'}, help_text='Required. 150 characters or fewer.', max_length=150, verbose_name='username'),
        ),
    ]
