# render.yaml
services:
  - type: web
    name: primeorgabicsbackend
    env: python
    region: oregon  # Choose the region closest to your users
    buildCommand: |
      # Install dependencies
      pip install --upgrade pip
      pip install -r requirements.txt
      
      # Run migrations
      python manage.py migrate
      
      # Collect static files
      python manage.py collectstatic --noinput
    startCommand: gunicorn primeorgabicsbackend.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true  # Automatically generate a secure secret key
      - key: PYTHON_VERSION
        value: 3.11.0  # Specify your Python version
      - key: DATABASE_URL
        fromDatabase:
          name: primeorgabics-db
          property: connectionString
      - key: FRONTEND_URL
        value: "https://primeorganics.vercel.app"  # Update with your frontend URL
      - key: DEFAULT_FROM_EMAIL
        value: "noreply@example.com"  # Update with your email
      # Add these if you're using email
      - key: EMAIL_HOST
        value: "smtp.gmail.com"  # Update with your SMTP server
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_USE_TLS
        value: "True"
      - key: EMAIL_HOST_USER
        sync: false  # You'll need to set this manually in the Render dashboard
      - key: EMAIL_HOST_PASSWORD
        sync: false  # You'll need to set this manually in the Render dashboard
    autoDeploy: true  # Enable auto-deploy on push to the main branch
    healthCheckPath: /api/health/  # Add a health check endpoint to your Django app

databases:
  - name: primeorgabics-db
    databaseName: primeorgabics
    user: primeorgabics_user
    region: oregon  # Choose the region closest to your users
    plan: free  # Adjust based on your needs (free, starter, etc.)