services:
  - type: web
    name: primeorgabicsbackend
    env: python
    region: oregon  # Choose the region closest to your users
    buildCommand: |
      # Install dependencies
      pip install --upgrade pip
      pip install -r requirements.txt
      
      # Run migrations
      python manage.py migrate
      
      # Collect static files
      python manage.py collectstatic --noinput
    startCommand: gunicorn core.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true  # Automatically generate a secure secret key
      - key: PYTHON_VERSION
        value: 3.11.0  # Specify your Python version
      - key: DATABASE_URL
        fromDatabase:
          name: primeorgabics-db
          property: connectionString
      - key: DB_NAME
        value: "primeorgabics"
      - key: DB_USER
        value: "primeorgabics_user"
      - key: DB_PASSWORD
        sync: false  # Set manually in Render dashboard
      - key: DB_HOST
        value: "dpg-XXXXXX.render.com"  # Update with your actual Render DB host
      - key: DB_PORT
        value: "5432"
      - key: FRONTEND_URL
        value: "https://primeorganics.vercel.app"  # Update with your frontend URL
      - key: DEFAULT_FROM_EMAIL
        value: "primeorganics.co.ke@gmail.com"
      # Add these if you're using email
      - key: EMAIL_HOST
        value: "smtp.gmail.com"
      - key: EMAIL_PORT
        value: "587"
      - key: EMAIL_USE_TLS
        value: "True"
      - key: EMAIL_HOST_USER
        sync: false  # Set manually in Render dashboard
      - key: EMAIL_HOST_PASSWORD
        sync: false  # Set manually in Render dashboard
      - key: PORT
        value: "8000"  # Ensures correct port binding on Render
    autoDeploy: true  # Enable auto-deploy on push to the main branch
    healthCheckPath: /api/health/  # Add a health check endpoint to your Django app

databases:
  - name: primeorgabics-db
    databaseName: primeorgabics
    user: primeorgabics_user
    region: oregon  # Choose the region closest to your users
    plan: free  # Adjust based on your needs (free, starter, etc.)
